### PR TITLE
James design views

### PR DESCRIPTION
**Pull request by gojamesgo85**
Added custom font

Added active mesh gradient background.

Added new Secondary color palette.

### CODE REVIEW

**Comment by gojamesgo85** [comment]
This is still a work in progress.

**Comment by gojamesgo85** [comment]
Screenshot 2024-08-24 at 12 37 12 AM

here's a dark color palette that I like. I just like the gold because of the card border. I really like this font . I think it looks like a font that would be in a good cocktail book. 

Screenshot 2024-08-24 at 12 39 44 AM

**Comment by gojamesgo85** [comment]
Moved CocktailList search bar and added formatting.

Removed the "Custom" label.

**Comment by gojamesgo85** [comment]
Saving manually is really important most of the time with SwiftData. This is something I've learned building this app. So, keep an eye out for it in the future.

SwiftData's auto-save is designed to automatically persist changes at certain points like when the app goes to the background or during low-memory situations. It's meant to reduce the need for manual save calls. 

Manually though, you can handle errors and get immediate persistence. 

Any hoodle, just an observation.

**Comment by MatthewHunt84** [comment]
That's weird, it's supposed to autosave after any model changes, and after each run loop

https://developer.apple.com/documentation/swiftdata/modelcontext/autosaveenabled
https://www.hackingwithswift.com/quick-start/swiftdata/when-does-swiftdata-autosave-data 

What are the situations where things aren't saving?

**Comment by MatthewHunt84** [comment]
Did some reorganizing and cleanup. Nothing changed besides code organization
One more thing on this before we merge - “Historical cocktail info” should be a button on specific historical cocktails recipe views instead of on the cocktail list title. See if you can find a good place to add that to the recipe views themselves (on the cards, rather than on the title)

**Comment by gojamesgo85** [comment]
Also, moved the historic cocktail explanation to recipe view. The question mark flag next to recipe is only on cocktails with the .originals collection tag.

**Comment by gojamesgo85** [comment]
Added swipe to delete hint that shows up only when creating a riff cocktail.

**Pull request merged**
