### PR TITLE
Multiple spirits button

### PR DESCRIPTION
**Pull request by gojamesgo85**
I added a"Configure Results" menu button with pop-out options. It's a very clear and concise way to convey our intention with the functionality. I like it very much. Now, as with everything else, we just have to work on the styling. It's at the bottom of the screen, which I also like. 

Screenshot 2024-01-16 at 3 20 18 AM

The multiple spirits search was actually all fucked up. So I had to go through it with a fine tooth comb to figure that shit out. I ended up writing everything out to figure out the problem. I had to rewrite some functions. So I'll need to refactor them so that they're less verbose in the future but at least it works. 

Here's how the multiple base spirit function goes:

We start by looping over each cocktail in Starting cocktails. 
The starting cocktails are all of the cocktails minus the unwanted ones. 
The first cocktail goes over every container in final match containers to see if it finds a match.

Say we’re looking for London dry gin, green chartreuse, lime, and rye whiskey.
The number of containers it will produce is 4 because the base spirits are two and the modifiers are 2 and we can’t show results for less than a 50% match. 

Example of results:
Container 1 has a match # of 3 with a preferred count of 3 and a base spirit of Gin (London Dry)
Container 2 has a match # of 2 with a preferred count of 3 and a base spirit of Gin (London Dry)
Container 3 has a match # of 3 with a preferred count of 3 and a base spirit of Rye Whiskey
Container 4 has a match # of 2 with a preferred count of 3 and a base spirit of Rye Whiskey

It goes over the first container to see if the match # = the cocktails match # by entering the cocktail into a reduce function called countMatchesForMultipleSpirits.
It starts with a count of 0
It goes over each CocktailComponent in the cocktail by starting with the booze components and compares them to only base spirits.
It then finds those matches and puts them into a JustBases array
A new for loop then starts. With component in SelectedPrefferedIngredients()
Then we check for spec in justBases to see if one of the bases matches the component.name. If it does, the count goes up by 1 but never goes higher than one
Checking against the same component, we check to see if it matches any of its other tags, if it does, it gets another +1.
After the component loop is finished, we send back the total matches with the specific cocktail.
If it matches the # of matches for the container as well as the base spirit that the container was assigned, then the cocktail gets appended to the container that it matches. 

Then the loop repeats for the next container until it goes through all 4 containers. 

 Here's the function that I need to clean up: 

Screenshot 2024-01-16 at 3 25 55 AM

### CODE REVIEW

**Review by MatthewHunt84 — CHANGES_REQUESTED** [review]
Damn, you posted this 2 hours before I had to get up for work lol

Okay, I like it - here's what I'm thinking:

image

I like the new UI at the bottom, but this is still not as obvious to a user as it could be.
How about "Sort Results" with the options "by spirit" and "by number of matches"?

I think that's about as obvious as we can make it.
We also will want to only show that button if multiple spirits exist in the search terms. If there's only "Gin" in the search, we don't want to give them the option to sort by spirit, we'll just default to sort by number of matches.

With the basic search right now there's a bit of an issue that I'm noticing as well.

Right now it's written from the perspective of somebody with different types of ingredients on hand. For example "I have gin, lemon juice, rasperry syrup, and egg whites" and that will show a clover club as a 4\4 match. But if if a bartender is entering ingredients that their guest enjoys and does "gin, lemon juice, egg (whole) and raspberries" it will only show as a 2/4 match. This is because Raspberries != raspberrySyrup and egg (whole) != egg white. 
So I think basic search needs to be split into 2 different views. One that is search by ingredients, and one that is search by flavors. That way somebody is able to search by raspberry and egg and be sure to match a clover club.

As for the new sort function, it works which is great. When you're ready to tackle refactoring it, it is a good candidate for reduce - but for now lets focus on the issue above since that's more critical. Refactors can come later

**Comment by gojamesgo85** [comment]
Help! Im going to bed defeated. I was wondering if you could give me some guidance on how you would go about debugging this issue. Here's what I've done so far:

Why don't flavors in the basicListView toggle their preferred Bool when toggled in the view?

Checked flavors in SearchCriteriaView. Those are producing results when toggled. ✅
In SearchCriteriaViewModel, I’ve checked to make sure the method that adds CocktailComponents to the array of components that populates the BasicListView is working correctly. It is. I’ve added a print statement to SearchCriteriaViewModel.createBasicComponentArrayForFlavors(). It prints out all the flavors as a CocktailComponents with their respective bool (isFlavor) marked true. ✅
I’ve added a print statement to GetFilteredCocktails() to print components for selectedPreferedIngredients(). All the selected booze components show up but the flavors aren’t because their isPreferred bool is not being set to true when toggled in the view. ❌
The same PreferencesCheckListCell is being used for all toggle preferences in every list. So they all have a binding to the component that should toggle isPreferred. ✅
The inits are all solid on CocktailComponents because they’re working everywhere else. ✅

I think I'm bad at debugging stuff. I don't want you to solve this for me but rather, how would you think about going further in the debugging process?

Any guidance would be greatly appreciated   🙏

**Comment by MatthewHunt84** [comment]
No worries man, look at the selectedPreferredIngredients() method - you'll figure it out from there.

**Comment by gojamesgo85** [comment]
Everything should work fine from a functional standpoint. Merge it in if you're ok with it and I'll work on refactoring some code.

**Pull request merged**
