### PR TITLE
Add ingredients funtionality

### PR DESCRIPTION
**Pull request by gojamesgo85**
you can add ingredients.

I merged the view models.

### CODE REVIEW

**Comment by gojamesgo85** [comment]
We now have basic functionality to add custom cocktails to the list view.

For not, I have them organized at the top. This actually might be a good way to do it so that the user has their cocktails shown first. But we can talk about how we'd like to organize them later. For now, this is where they live. 

Screenshot 2024-03-03 at 1 03 32 AM

They also have a swipe to delete feature. We might want to make this a lockable feature so that someone doesn't just get into your phone and delete all your hard work. 

Screenshot 2024-03-03 at 1 05 33 AM

The add ingredients for also has swipe to delete. 

Screenshot 2024-03-03 at 1 07 48 AM

I haven't built out the build order part yet. But I'll work on that next. For now, the cocktails are being saved to SwiftData and are shown in the list view.

**Comment by gojamesgo85** [comment]
You can add an array of garnish now. 

Garnish is a menu. 
Added garnish populates below the "Add Garnish" button. 

Garnish also has swipe to delete.

**Review by MatthewHunt84 — CHANGES_REQUESTED** [review]
Great job, now lets clean up a couple of things.

Pull first cause I made a few changes

1. add view blocks like this to their own structs.
For instance, this block here should be inside AddedIngredientsView
image
(move into here)
image

Same with the garnish view. The idea is that the high level views should be really easy to read like this:

image

Also right now, the add hitting add ingredient on that view will just re-add the last added ingredient, instead that should show an alert saying we're missing info.

REALLY GREAT WORK THOUGH!

**Review by MatthewHunt84 — APPROVED** [review]
Perfect!

**Pull request merged**
