### PR TITLE
Unmatched results filtering

### PR DESCRIPTION
**Pull request by gojamesgo85**
Filtering now works on each individual section of the search results. I really like the idea of limiting the filter options to one ingredient.

This also did something unexpected but super cool. It got rid of the need for the separate split base cocktail search. It effectively made it useless because now you can search for the split based type cocktail that you're looking for and an option will either show up or you can search for the same criteria but filter the results to omit whichever base spirit that you'd like to show results for. 

A good example for this is the Smoking Monkey Cocktail. Search Whisk(e)y + Lemon + Gin + Egg. The Smoking monkey is at the top, then the user can filter individual spirits out while the other ingredients remain.

This also cleans up a ton of unnecessary code from the view model and results view. How neat!

The way I achieved it was actually pretty simple. I added a nonMatchPreferencesArray directly to the cocktail object.

Screenshot 2024-04-05 at 12 14 52 AM

Then I added a small function that checks the selected preferences against the cocktail's ingredients. 

Screenshot 2024-04-05 at 12 16 39 AM

Then we run that function right before the cocktail gets added to the ResultViewSectionData to append the ingredients that don't match the specific cocktail.

Screenshot 2024-04-05 at 12 19 31 AM

Then the filtering  just happens on the COCKTAILRESULTSLIST view.

I'm pretty happy with this change so thank you for the guidance. 

I left the old code grayed out in case you want to change things.  But let me know what you think! 😀

### CODE REVIEW

**Comment by MatthewHunt84** [comment]
Nice work man!

Before this gets merged, there's an improvement I'd like you to try and make:

Storing the missing component on the cocktail object is convenient, but unfortunately it is not good architecture.

We want model objects to store saved information, rather than temporary info like this. It just causes a lot of unnecessary loading and saving to the model, and this view loads super slowly on my simulator and I think these extra model steps are the cause.
I want you to try and come up with another solution. You could do something like a missingIngredient class that holds an ingredient and an array of cocktails like I talked about the other day, or anything else that works - we just want to stay away from adding non-permanent information to model objects

**Comment by gojamesgo85** [comment]
Ok. So, I removed the missing components array from the cocktail object and slightly modified the ResultSectionViewData class to take in and array of the new CocktailsAndTheirMissingIngredients class in place of the regular array of cocktails. 

Screenshot 2024-04-06 at 9 47 56 PM

This way, I can still add the missing ingredients to the cocktail without it being attached to the cocktail object. 

Now, in getFilteredCocktailsSwiftData(), when it adds the cocktail to the correct data shell, it also adds the missing ingredients but running the function below. 

Screenshot 2024-04-06 at 9 50 27 PM


Let me know if this is ok or if I need to change anything.

**Review by MatthewHunt84 — CHANGES_REQUESTED** [review]
### _UPDATE: This is getting too hard to explain, I'm just gonna do it and put up a PR. See bottom for your next task_
_Leaving comments below so you can see what I changed and why:_

FindUnmatchedComponents takes too long because there are too many loops happening where they don't need to.

Take a look at selectedPreferredIngredients() first, this is being called all over the place causing a bunch of loops when the first one should be enough. See if you can store the array the first time it's run and only override it once the search criteria changes.

Second, convertTagsAndSpecToStrings is a loop that is run more than it needs to as well.

We just called it on line 219 in countMatches, before findUnmatchedComponents is run on line 220 and it has to loop through everything again. This one is a little trickier to fix because there is a LOT happening on line 219.

So for that line, first up selectedPreferredIngredients should be an array once you're done with fixing that. Once that has been taken care of, let's look at the two places where convertTagsAndSpecToStrings is run.
First up is the countMatches function. This is a predicate we wrote to pass to the reduce function. I forgot we did this, it's pretty slick but I can see how it would be confusing a little to look back on so for clarity: the reduce function is just trying to reduce down to an integer for us, it doesn't care how. So it starts at 0, then runs the countmatches function (passing in that 0 as $0 for the currentCount, and loops through each of the preferredComponents (passed in as $1) and then updates the currentCount if it finds a match. Once it has checked all of the preferredComponents it returns the final count. Inside that function we're using convertTagsAndSpecToStrings to match strings in the spec to names of the preferred ingredients.

Then immediately after doing that, on line 220 we do this findUnmatchedComponents which again uses convertTagsAndSpecToStrings to find ingredient names NOT found on the cocktail object.

So both of these functions are running for every cocktail in the loop, and then looping through two loops each (FindUnmatchedComponents, and convertTagsAndSpecToStrings) for each cocktail. So there are literally thousands of loops running from line 219 to line 220 which isn't great.

So the first fix I mentioned already is to store the selectedPreferredIngredients as an array.
The second fix is to essentially combine countMatches with findUnmatchedComponents, where we piggy back off countMatches, and when we find an ingredient that dosen't match we throw those ingredients into an array on the viewmodel. We can then use that missing ingredient array when we make our CocktailsAndMissingIngredients object without adding in another whole series of loops. Then we wipe that array for each cocktail, rinse and repeat.

**Okay, what I do want you to do is fix this: When we view a cocktail in that list, and back out of it - it runs the whole getFilteredCocktails thing again. See if you can find a way to store that info so we don't have to run all this every time we look at a cocktail and back out**

**Comment by gojamesgo85** [comment]
Popping the recipe view off of the stack no longer triggers getFilteredCocktailsSwiftData().
The search button only appears when shouldShowSearchButton() == true.

**Comment by gojamesgo85** [comment]
Popping the recipe view off of the stack no longer triggers getFilteredCocktailsSwiftData().
The search button only appears when shouldShowSearchButton() == true.

**Comment by gojamesgo85** [comment]
Popping the recipe view off of the stack no longer triggers getFilteredCocktailsSwiftData().
The search button only appears when shouldShowSearchButton() == true.

**Pull request merged**
