### PR TITLE
Recipe view bug fixes

### PR DESCRIPTION
**Pull request by gojamesgo85**

### CODE REVIEW

**Comment by gojamesgo85** [comment]
Can't figure out the back button. When I try to attach it to IngredientRecipeView directly, Xcode get's mad and the button doesn't work. I think it's something to do with the way viewModel.flipCard() gets called and the beginning of the animation trying to start. But I'm not really sure.

**Comment by gojamesgo85** [comment]
Ok so, I took away the Historic cocktail link to anything that didn't have n Author. Because, the modal says that it's an original recipe, unchanged from its original publication. So, unless there's a cite, there's no publication. So if there's no cite, it's our take on the classic, and we make a note button that explains the difference between that version and the original. I did that for any cocktail without a cit AND i took away the .original tag from cocktails without a cite.

**Comment by gojamesgo85** [comment]
On Jasmine Tea Gin in "A Whole New Wold", check out the position of the back button.

**Comment by MatthewHunt84** [comment]
Replaced the ZStack with a Grid which works much better. Still seeing the weird title bug but I'll fix that soon

**Pull request merged**
