### PR TITLE
Simplified Full Batch View

### PR DESCRIPTION
**Pull request by gojamesgo85**
Changed functionality of full batch view.

### CODE REVIEW

**Comment by gojamesgo85** [comment]
Full batch view now shows how many of each bottle (750 or 1L) you would need for each ingredient. 

You can round up or down to the nearest bottle with their respective round up or down buttons.

**Comment by gojamesgo85** [comment]
Everything functions the right way. Working on animation bugs and layout.

**Comment by gojamesgo85** [comment]
Added styling to CBC.

**Comment by gojamesgo85** [comment]
Smoothed out the animation on BatchCellView by changing the list on QuantifiedIngredientsListView to a ScrollView with a LazyVStack. I learned a ton about lazy loading vs regular a VStack which renders all of its children immediately, regardless of whether they are visible or not. So when showBottleMath on BatchCellView was toggled, the view would snap in and out immediately causing a jarring effect.

**Comment by gojamesgo85** [comment]
I really like where it's at now. Feel free to merge it in unless you want me to change anything. if not, I can work on SplitBatchView next.

**Comment by MatthewHunt84** [comment]
I pushed up a few changes to the padding and layout. 
Just go through and clean things up, there's a lot of commented out code in this PR.
Also, would you double check the add ingredient and add garnish buttons? They weren't working for me but not sure if that's related to this PR at all

**Comment by MatthewHunt84** [comment]
But great work otherwise, this is much better

**Pull request merged**
