### PR TITLE
Add ingredient with new model

### PR DESCRIPTION
**Pull request by gojamesgo85**
You can now properly add custom ingredients to custom cocktails. You can even add build step instructions.

### CODE REVIEW

**Review by MatthewHunt84 — CHANGES_REQUESTED** [review]
Great job man!

I'm going to request a few changes though to give you some stuff to do, but I think it will 

I think we should split this into two views - one for selecting from existing ingredients, and then one to create a new one. It's less confusing that way.

The first view will allow a user to select from existing ingredients, its title will be "Add Ingredient" which should show up top like it does here:

image

We'll remove a couple of the "add new ingredient" features so this is just selecting from a list, and the button at the bottom will be the "create new ingredient" view.

image

When they click "Add ingredient" and this will be exclusively for creating new ingredients and should look like this:

image

Bonus points:

You don't need to do this, but I think it would be good to filter the measurement unit menu a bit depending on what category we're in - think wet and dry, so if we're adding a type of vodka we wont show "leaves" or "pinch", but vice versa for dry ingredients (no "oz", "dashes" etc for mint leaves. This shouldn't need to change on the model, just on the logic for creating that menu.

Killer job so far, appreciate all the work you've been putting in this week

**Comment by MatthewHunt84** [comment]
More bonus points:

I also think it would be a good idea to add one more optional variable to the Ingredient model, which would be "Info"
In a cocktail spec on the Cocktail page we could then show a little question mark icon if the ingredient was a bit more obscure.
For instance, right now Aberlour Abundah wraps onto two lines like this:

image
image

In the new system, it would just be "Aberlour abundah" in the ingredients view, and it the cocktail view it would be the same but with a little question mark next to it. If the user clicks the question mark it would expand (just toggle a new Text view below) and say "a high proof single malt" or whatever so that somebody that doesn't know it could find a suitable replacement in a pinch. I don't think it needs to give any more info than that - people can google it if they need to, we just want to help out a bartender on the fly.

So this would involve adding it to the model as an optional which should be easy:

image

image

image

If the user taps the button it toggles the Ingredient view to add a new line below the ingredient with the info string, with forgroundStyle(.secondary) or something.

**Comment by MatthewHunt84** [comment]
And last thing, you currently have some constraint warnings on this view. As you refactor, make each piece into its own view so you can compose them together. This will make the code cleaner, and help to isolate the part that is causing issues.
Ideally in the end you want to have something really easy to read like:

    struct AddIngredientView()

     @StateObject var viewModel: IngredientViewModel (or whatever, just some common place to store selections from the views)
     
     init(cocktail: Cocktail) {
        self.viewModel = viewModel(cocktail: Cocktail)
    }

    var body: some view {

    NavigationStack {
    
    VStack {
        
        AddIngredientSearchView(viewModel)
        AddMeasurementView(viewModel)
        AddStepsView(viewModel)
        AddToCocktailButton(viewModel) <-- this will have an action that adds the new Ingredient to the cockatil.spec array)
        CreateNewIngredientButton(cocktail: viewModel.cocktail)  <-- this will push to the new "Create Ingredient" view 
        abandoning the viewModel (since we don't need it) but passing along the Cocktail (which we will need)
        }
        .NavigationTitle("Add Ingredient") <-- or however the title is set up, might not need a Nav Stack just whatever is simplest
       }
    }

**Comment by gojamesgo85** [comment]
I'd like to back up a bit and focus on getting the ingredients list to load from a refined @Query of the existing cocktails so that we can properly show all existing ingredients, even custom added ones.

I have the bare bones working so far. It does what we need it to do but it's sloppy and slow. I need help with the way we'd use higher order functions to refine the ingredients from the query. Here's how I'm doing it so far:

Screenshot 2024-07-07 at 7 18 13 PM
When ADDCOCKTAILVIEW is first loaded, we load all of the ingredients onto a var on the viewModel that's just an empty array of [Ingredient]. It only loads this one time but it takes way too long to load. So I know I'm doing it wrong. 
Here's what the method looks like:
Screenshot 2024-07-07 at 7 21 18 PM
I know this should be all higher order functions, but I could only come up with a mix between them and basic looping. 
This is the slowest part of the process and the part we need to refine the most. 
The things that are making this difficult are:
1. I cant just cast this array as a Set because all the ingredients include several differing values that make them unique. So we'll still end up with 50+ Lemon Juices for example.
2. The initial @Query is adding every ingredient from every cocktail. So it has to sort through thousands of ingredients, event though many of them share the same name. 

Next, the list that is shown for existing ingredients only starts populating matches after the user starts typing in the desired name. I've added a "matchesCurrentSearch" bool to make it easier to filter through existing ingredients. 

Screenshot 2024-07-07 at 7 25 06 PM

If the user decides to create a custom ingredient, it will add it to the cocktail then the user can add the cocktail to the ModelContext. 
After it's added to the model context, the next time the user wants to add an ingredient, the custom ones show up in existing ingredients.

**Comment by gojamesgo85** [comment]
I refactored ADDEXISTINGINGREDIENTDETAILVIEW and ADDCUSTOMINGREDIENTVIEW to find out what the constraints issue was. 

It's the KeyboardDoneButton. Something about the width being 0. The warning comes up but it's not breaking anything. Any idea how to fix that one?

**Comment by gojamesgo85** [comment]
Measurement units change dynamically based on chosen category. 

Screenshot 2024-07-08 at 12 46 06 AM

**Comment by gojamesgo85** [comment]
Screenshot 2024-07-09 at 12 09 56 AM

I'm still trying to figure out how to get the animations to line up.
Go to cocktail "Faker Face" to see the animation inconsistencies.

Here's where I put the logic for the optional info. 
Screenshot 2024-07-09 at 12 12 25 AM

**Comment by MatthewHunt84** [comment]
Ignore the fact that a million files changed, that was just from renaming CocktailIngredient to OldCocktailIngredient so you know what not to use anymore. 
I gotta get to work but take a look at the other changes and we'll talk about things at 4pm!

**Comment by gojamesgo85** [comment]
It builds fine, but crashes when you select a cocktail from CocktailListView.  Here's the crash info:

Screenshot 2024-07-09 at 7 44 22 PM

**Comment by MatthewHunt84** [comment]
So the issue was with the remove duplicates function I wrote - it removes duplicate IngredientBases but in the process, but the Ingredients that depend on the duplicates don’t just reference the new one, they lose theirs completely and this breaks the model. My bad!

 I can fix the underlying problem by writing a more involved initializer for Ingredient to be used during preload (so while we’re populating the model, each time we go to create an IngredientBase we first check if that specific IngredientBase already exists, instead of creating a new one). This should allow for us to add the #Unique(\.name) property to IngredientBase as well which will solve this issue from recurring in the future.  I'll do that, but I have a good enough fix for now which just removes duplicates on the query when we go to use it.
 
If you can confirm that the crash is fixed we can merge this in.

**Pull request merged**
