### PR TITLE
Search view updates

### PR DESCRIPTION
**Pull request by gojamesgo85**
Started to restructure search view. All new views are under "SearchViewWithDataQueries" group.

Right now, it only searches based on IngredientBase. So the queries are very limited.

Also, the search is rather slow. 

I know I have a lot to learn here, but it's a start.

### CODE REVIEW

**Comment by gojamesgo85** [comment]
Added "isPrefered" and "isUnwanted" Bools to IngredientBase in hopes that it would make the search faster. It's sort of faster but still slow.

**Comment by MatthewHunt84** [comment]
You're doing great man! This is harder than I anticipated.

It will be faster I think if we use queries to filter out the cocktails as we move into the next view. Take a look at this for inspiration: (I know this is on the wrong view, I just wanted to show it working)

Pasted Graphic 20

Now imagine the application where we pass an array of values that are preferred and notPreferred into the CocktailResultListDataQueries. It takes those values and makes expressions for them. Then we make a predicate for each query we want and when the view loads we map those queries into the appropriate buckets.

See if you can get a query to work this way ONLY for perfect match cocktails for now. Then we can add logic for those that match with missing ingredients afterwards.

**Comment by gojamesgo85** [comment]
I created a very basic flow that should show the filtered cocktails on CocktailResultListDataQueries when you hit the "Search for Cocktails" button.

I'm getting a confusing error:
"Query encountered an error: Unsupported Predicate: Captured/constant values of type 'IngredientBase' are not supported"

There are only variables on IngredientBase Model. I don't understand what the Captured/constant values are. 

any ideas?

**Comment by gojamesgo85** [comment]
Screenshot 2024-07-16 at 11 12 23 PM
I've created several Expressions for several predicates for several Queries for testing. They are all contained in a single init which might be the issue? But I'm not entirely sure.

Each expression and predicate goes with their corresponding Query.

Though, the only query that seems to be working is the one for 100% matches. Those are the only ones getting through.

I'll leave the print statements in for your own testing. 

Here's where the Queries are getting called:
Screenshot 2024-07-16 at 11 17 21 PM

Here's the function that is supposed to separate the individual queries and fill the corresponding ResultSectionViewData:
Screenshot 2024-07-16 at 11 23 13 PM

the sections that aren't a perfect match are supposed to fire off the "FindMissingIngredients" func. But it never fires because it's only loading the cocktails with perfect matches.
Screenshot 2024-07-16 at 11 25 42 PM

My theory is that the init can't handle more than one Query or predicate? I don't know. I'll see if I can come up with something before I go to bed but I'm just guessing at this point.

**Comment by gojamesgo85** [comment]
I gave each section it's own view with its own individual init, expression, predicate, and query. They all had very different names. I event separated the functions in the view model that populated each section with the corresponding cocktails. And still, only the initial query worked.

Whichever Expression in an init for the view works first, is the only one that it will accept. 

Here's the first separated view:
Screenshot 2024-07-17 at 1 11 18 AM

Here's the second:
Screenshot 2024-07-17 at 1 12 29 AM


here's how i separated the functions to insert the sections:
Screenshot 2024-07-17 at 1 13 38 AM


It seems like a massive bug. But hopefully I'm wrong.

**Pull request merged**
