### PR TITLE
Stuck on passing information to batch view.

### PR DESCRIPTION
**Pull request by gojamesgo85**
Recipe view owns Recipe view model which owns the cocktail information.
That gets sent to RecipeFlipCardView to be displayed in SpecView. 
Also, a binding Bool gets sent to SpecView that RecipeFlipCardView initiates so that when the user selects the Batch button, it toggles the binding bool and shows the prompt to ask how many cocktails they want to batch. 
The FloatingPromptView gets triggered and the user adds the number of cocktails which is bound to viewModel.NumberOfCocktailsText and should show up in the next view. 

The issue:
When I hit batch, the information isn’t presented on CBCLoadedCocktailView. It just shows the default “Test” as the name. 

I have a print statement that triggers when it loads that shows that the information is being sent to the view but for some reason won't cooperate?

Any ideas?

### CODE REVIEW

**Comment by gojamesgo85** [comment]
Got the initial number to come through. Now,  when I change the cocktail count on the textField in CBCLoadedCocktailView, it won't update the view. It updates the viewModel I think but there's nothing triggering the refresh on this view. 

I feel like my skills are declining. I'll keep working on it but I'm feeling discouraged.

**Comment by MatthewHunt84** [comment]
Hmmm, it seems like you're passing CBCViewModel around as both a binding into the child view, AND as an environment object. You need to pick one strategy (I would say environment object makes the most sense). 
Fixing that viewModel i think is what's going to make things work.

Also don't forget to make the viewmodel's var @published if you want the changes to show up on the views - you only get that for free using @observed and importing the Observable framework (or SwiftData which imports it behind the scenes). But if you're going the @environment object route i think the viewmodel has to be an @observedObject - so you'll need to declare the @published vars.

I know its confusing, but I hope this helps a bit

**Comment by gojamesgo85** [comment]
Functionally, I think the batching calculator works the way you want it to. 

Play around with it. Let me know if you want me to change anything.

**Comment by MatthewHunt84** [comment]
I'm seeing a bug
- select the intial 100 cocktails
- change cocktail count in batching screen
- values don't update
- then change dilution
- app crashes
image

**Pull request merged**
