### PR TITLE
Added some cocktails. I got past 'E' in classics! Progress.

### PR DESCRIPTION
**Pull request by gojamesgo85**

### CODE REVIEW

**Comment by gojamesgo85** [comment]
I also made sure that the toggles resize properly in landscape for iPad.

**Comment by gojamesgo85** [comment]
Screenshot 2024-01-25 at 4 12 16 AM

to the right of the Cocktails title in the COCKTAILLISTVIEW is a new button. It's a cog that has a drop down menu for "bartender mode" or "Guest Mode"

either one toggles a bool in SEARCHCRITERIAVIEWMODEL called "menuMode"

It triggers what will display when you click on any cocktails in the app either from the list or from a search.

"Bartender Mode" will show exact specs for cocktails, glassware, ice, garnish etc.
"Guest Mode" will show a picture of the glass, give you the names of the ingredients as well as the profile of the cocktail. 
Image assets have been added for all glassware types.  So for now, there's a temporary image of at least the glassware type . 

Both modes show the author if there is one.

I've also consolidated "Textures" into "Profiles"
All the textures we had listed work just as intuitively in profiles. It takes more sense to have them consolidated. We no longer have the issue of "Creamy(Profile)" and "Creamy(Texture)". Textures are indeed a part of the profile of the cocktail.
It also means there's one less tab to drag through in the advanced search. 

I've edited all of the tags on the 130 cocktails to reflect the change. 

I fell like it's much more concise now. 

I did a lot, again. So let me know what you think!

**Review by MatthewHunt84 — APPROVED** [review]
Great work man, I really like the change to textures as well. 
The assets look good too, even if they're just a placeholder until we can get something professional and custom made.

The menu mode is cool, but let's talk about what your plan is a little more. The only small change I think we should make before merging is to change smallHighball into fizz glass - since that's a common enough term.

Great work man, you're killing it

**Comment by gojamesgo85** [comment]
I moved all the glassware logic to COCKTAILMENUVIEWMODEL.

I'm not sure I understand why the Cocktail in RECIPEINGREDIENTSVIEW needs to come from a different view model. Or maybe I'm just not understanding the intention here. 

It's already coming from a viewModel in the previous screen, as seen below:

Screenshot 2024-01-25 at 12 54 36 PM

Both RECIPEINGREDIENTSVIEW and COCKTAILMENUVIEW are receiving their cocktail object from  COCKTAILLISTVIEWMODEL.

Let me know if I'm missing something here.

**Comment by gojamesgo85** [comment]
I don't think we should make the sections for spirits and N/A expanded initially.  My reasoning is the ease of navigation. It negates the need for a search bar because you just search by category, pick the one you want and there ya go.  If we expand all of them to start, the screen is overwhelming and all you see at first is Agave. You'd have to do a lot of scrolling to get to where you want. Or, you'd have to search with a search bar or alphabet nav or something to find what you want. Having the collapsed sections initially makes it much easier to navigate.  If you feel strongly about it, we can talk about the execution whenever you'd like.

**Comment by MatthewHunt84** [comment]
So the idea for the viewModel is that CocktailMenuView will get initilized with a single object. That object will be it's viewModel which will handle everything. We can also do it the way it is now, but it's cleaner with a single piece. 

So the architecture I'm looking for would be:

The user selects a cocktail from the CocktailResultsList. On line 37 of that file, instead of passing a just a cocktail, we would instantiate the CocktailMenuViewModel object instead like this:
image

The CocktailMenuViewModel will then handle and logic behind what the  CocktailMenuView will show, and the CocktailMenuView will only be responsible for laying out those objects that it gets from the viewModel.

Inside the CocktailMenuViewModel we'll have a cocktail, and we can go ahead and instantiate the image right in the initialzer as well. If you're feeling fancy you could even add an image function directly to the Glassware enum, and pass it the ice from the cocktail like this:

image

And then the Glassware enum would get a function that looks something like this (If you can hardcode the logic, which may not be possible, just an idea):

image

**Comment by MatthewHunt84** [comment]
Yeah I think your reasoning is sound regarding the collapsed views. Let leave that how it is.

**Comment by gojamesgo85** [comment]
I made the requested changes. 

I felt it was easier to pass in the whole cocktail on the glassware func instead of just the ice to deal with the fact that Ice is an optional. 

Screenshot 2024-01-26 at 1 43 46 PM



Also, instead of initializing it, then adding that every time we call it, I feel like it's less code to just add it on the glassware image call site.

Screenshot 2024-01-26 at 1 44 32 PM

let me know if that's alright or if it's better to call it on the initializer.

**Comment by MatthewHunt84** [comment]
Lets put it in the initializer, so we can just call viewModel.cocktailImage from the view.

Otherwise we're calling the viewModel twice 

image

**Comment by MatthewHunt84** [comment]
Great work though! I think once we merge in the coreData changes from my end, we should add the ability to favorite cocktails as well. 

One more thing - what if for a cocktail with duplicate recipes (i.e Elks club, + Elk's club (williams and graham) ) - we made it so you could swipe left on a cocktail to see variations?

Just an idea, but I think it would be cool. Maybe even have the same thing for cocktails that are identical except spirit - i.e you could swipe left on the gin for a south side and a smash would slide in. Could be kinda neat

**Comment by gojamesgo85** [comment]
I made all the changes you’ve requested as well as the change to showing multiple recipes for one cocktail as a sliding view.

These new views are accessible from COCKTAILLISTVIEW. They are GUESTCOCKTAILLISTVIEW and BARTENDERCOCKTAILLISTVIEW. 

BARTENDERCOCKTAILLISTVIEW has access to every cocktail variation. So they’ll see more cocktail options than GUESTCOCKTAILLISTVIEW. 

This is because in GUESTCOCKTAILLISTVIEW, some recipes are so similar in ingredients that they look identical. 

To avoid the guest having to look through identical variations, I created two different cocktail lists that the views pull from in COCKTAILLISTVIEWMODEL

They are “guestCocktails” and “bartenderCocktails” as shown below. 
Screenshot 2024-01-27 at 3 23 48 AM



“bartenderCocktails” just compiles all of the cocktails from the GETBARTENDERVIEWCOCKTAILS() func 


 “guestCocktails” pulls from the GETGUESTVIEWCOCKTAILS() func with a modified dict excluding any duplicates that look seemingly identical in guest view. 

Screenshot 2024-01-27 at 3 51 05 AM


I’ve also changed the author to reflect modern recipes. So if its W&G’s version of the BrandyCrusta, then the author will say Williams and Graham so that the user knows where the recipe came from. 


The SEARCHCRITERIAVIEW will still use the old views (Not the slidey ones). This is intentional. 

When searching for a specific spirit, some cocktail recipes can be dramatically different in spec from one author to another. So we still want to list all the available variations. 

Bartender view will have all of the cocktails and guest view will still have the limited options to avoid finding identical recipes. 

I’ve changed the old single views names to SEARCHBARTENDERRECIPEVIEW and SEARCHGUESTRECIPEVIEW. 

I’m really digging the new view styles and the condensed cocktail variations. That was a great suggestion! And it only took me 14 hours :D . OH BOY! 

I should go to sleep now.

**Comment by gojamesgo85** [comment]
we should probably merge this branch in. There's 202 files changed haha.

**Comment by gojamesgo85** [comment]
I didn't really explain ALL of the work I did today. So let me know if you have any questions. about anything.

**Pull request merged**
