### PR TITLE
Sub categories show up in search terms

### PR DESCRIPTION
**Pull request by gojamesgo85**
***Queries are not connected yet.

I want to make sure I'm searching correctly before I move on to the next step. 

The subcategories only show up in the filtered list on the initial search view. 

first I made arrays on SearchViewModel for preferredSubCategories and unwantedSubCategories as well as an array of subCategoryStrings to check against.
Screenshot 2024-07-17 at 8 41 55 PM

then i made a function on the model to filter subCategories:
Screenshot 2024-07-17 at 8 43 04 PM

Then I made a PreferencesThumbsCellForSubCategories:
Screenshot 2024-07-17 at 8 44 05 PM

In ThumbsUpOrDownIngredientSearchList I stacked the subCategories above the filteredIngredientsList so that they would show up first because they are the more common search terms.
In the filteredIngredients list, I check to see if !viewModel.subCategoryStrings.contains(ingredient.name.wrappedValue) before adding PreferencesThumbsCell(viewModel: viewModel, ingredient: ingredient) so that the same term doesn't show up twice in the search.
Screenshot 2024-07-17 at 8 46 27 PM

Now we have a list of subCategories and ingredients to search with. The question now is how to work the expressions so that we filter cocktails correctly.

### CODE REVIEW

**Comment by MatthewHunt84** [comment]
Okay, having thought about it a bit more here's how I think we should do this part:

I like how you have the four potential arrays as just strings (preferred ingredients, not-preferred ingredients, preferred subcategories, and not-preferred subcategories) so lets just make the shared array of ingredients and subIngredients an array of strings. just combine their name strings into a big array.
_When you're doing this, add a print statement (just for us for debugging) to find any duplicated names. There might not be any, but we need to fix them if they exist). So that list will just be an array of strings._

Now we only need to run one matching function on type string, instead of two (on the Ingredient and subCategory types)

Then when the user clicks a thumbs up or thumbs on one of the cells, we just add a function where we:

- take that name and first see if it is a subCategory. This step should happen first because its the fastest (if it's a subcategory we move on quickly, instead of checking every single ingredient first)
- If it's not a subcategory we immediately add it to the appropriate ingredients array because it can't be anything else.

Then when the user hits search we continue passing those arrays to CocktailResultListDataQueries just like you have it now.

**Comment by gojamesgo85** [comment]
the fiter function now filters both ingredients and subCategories:
Screenshot 2024-07-18 at 5 22 48 PM

I condensed subcategories and ingredients (both unwanted and preferred) into one array each. Then on CocktailResultListDataQueries, I create unwantedSubCategories and preferredSubCategories on the init: 
Screenshot 2024-07-18 at 5 24 58 PM
This way is way less confusing when creating the code for adding and taking away items in the unwanted and preferred lists that would make up the PreferencesThumbsCells.

**Comment by MatthewHunt84** [comment]
Awesome job man!!

One last thing before I merge - lets give this Cocktail Result list view a title, and have it show the selected ingredients as well (that can be deselected in real time and the views below should update)

So basically this part should persist into the next view, with a new title ("Matched Cocktails" or whatever)

image

**Comment by gojamesgo85** [comment]
I've made almost all of the requested changes. I can't figure out how to update the view when the user taps on a preferred or unwanted ingredient.  Normally, the lists are populated in the view model, making it easy to update the view when the observed variables change. But the way it's set up now, the cocktails only change when the view is initialized.  Let me know how you think we should do this.

**Comment by gojamesgo85** [comment]
Screenshot 2024-07-19 at 1 48 32 PM
This function finds all of the ingredients that are connected to subCategories and populates them into unwantedIngredientsFromSubCategories or preferredIngredientsFromSubCategories depending on whats in unwantedIngredients or preferredIngredients.

So now we have access to the ingredients from subCategories without having to loop through all of the cocktails. 

The easy part is filtering out the unwanted cocktails:
Screenshot 2024-07-19 at 1 54 02 PM
we just add that expression to all of the predicates. 

That's already implemented. 

The part I'm still trying to figure out is how to include cocktails that included the ingredients from the sub categories as well as satisfying all of the other expressions while keeping the preferred count in mind so that preferencesListView get updated correctly. 

We can't just do the inverse of includesUnwantedIngredientsFromSubCategories expression (above) because if the user doesn't add a SubCategory to the search, then the expression will come back false and no cocktails will get populated. 
So, we have to be a bit more clever with adding cocktails with ingredients from subCategories.

**Comment by gojamesgo85** [comment]
I'm limiting the queries to arrays with up to -2 preferences until we refine the search function to reduce clutter.

**Comment by MatthewHunt84** [comment]
Okay, so these are interesting issues. Lets go one at a time:

First up lets look at the dynamic query problem. Once this is fixed we'll tackle the subCategories issues.

So right now, the query issue is that when we change the ingredients on the array (due to the "tap to remove" functionality) our query views don't update, correct? In swiftData, queries aren't dynamic (yet, I'm sure they will be in a few years) so we need to keep leaning on our initializer strategy!

Basically, _the queries need to happen directly on the subviews_ (totalMatch, minusOneMatch, etc). 

SwiftUI will re-draw the views anytime the data they depend on changes (so long as that data is published). So if the totalMatchView depends on an array of preferredIngredients and that array changes, swiftUI will trigger a redraw of that subview. 

This re-draw will re-run the initializer, and all the predicates will run again and the view should update.
I haven't tested this, but I believe that's the answer! We just need to move those queries down from thew CocktailResultListDataQueries view into the subviews themselves, and make sure each subview depends on a published array which will be updated by user interaction

**Comment by gojamesgo85** [comment]
The problem I'm having is when we need to show cocktails that aren't a perfect match, they rely on populating the cocktails from the ResultViewSectionData.cocktails rather than just directly from the Query ,like on perfect match cocktails, for the list so that the cocktails can show what ingredients they're missing and so the user can filter the cocktails based on the missing ingredient. 

the way I'm attempting to populate the cocktails section of the passed in ResultViewSectionData is on line 183 of CocktailResultListDataQueries in MinusOneMatchView via an .onAppear. 

What I think is happening is that the passed in ResultViewSectionData is getting initialized with an empty array and then the onAppear gets triggered, populating the array, but only after the view gets initialized. So, the results are not showing up. 

There isn't a way (to my knowledge) of populating the list on the init itself because minusOneMatchCocktails aren't available until after the init happens.  

Let me know if you can shed any light on the issue.

**Comment by gojamesgo85** [comment]
OK. I finally found the solution. 

The issue I was having was that I was trying to update "sections" in the viewModel and the views weren't updating. 

What I've learned:
Sections is an array of a struct with several variables. I was changing the internal variables of the structs in the array hoping that the views would update. This is where I went wrong. 
The views wont trigger an update unless you remove or add an entire item to the array. I.e., in this situation, I would have had to add or take away an entire ResultsViewSectionData, which isn't what we want. 

So, I broke it down into smaller chunks that the compiler could understand easier. 

On the view model, I created cocktailsAndMissingIngredientsForMinusOne and cocktailsAndMissingIngredientsForMinusTwo, which are [CocktailsAndMissingIngredients]. CocktailsAndMissingIngredients are the meat and potatoes of ResultViewSectionData. So those are what I update directly on task on each view and we use those to populate their respective lists. 

We don't need to create those for fullMatchCocktails because they have no missing ingredients and are populated directly from the @Query in the view. 

Because we know exactly how many preferences are missing for each array of cocktails, we can just fill in the necessary information to the section headers manually and we don't have to rely on the array of ResultViewSectionData ("sections") in the viewModel to populate our lists.

**Pull request merged**
